name: initiative_tracker
description: A sample web application
dependencies:
  browser: any
  core_elements: any
  paper_elements: any
  polymer: any
dev_dependencies:
  scheduled_test: any
transformers:
- polymer:
    entry_points: web/initiative_tracker.html
